server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location = /grades {
        return 301 /grades/;
    }

    location /grades/ {
        try_files $uri $uri/ /grades/index.html;
    }
}
