export const AREA_LIMITS = {
  basis: 24,
  schwerpunkt: 30,
  ergaenzung_econ: 24,
  ergaenzung_mss: 12,
  thesis: 30
};

export const MODULE_DATABASE = [
  // Basisbereich
  { id: 'bm_math', name: 'BM Mathematics', lp: 6, areas: ['basis'] },
  { id: 'bm_micro', name: 'BM Microeconomics', lp: 6, areas: ['basis'] },
  { id: 'bm_macro', name: 'BM Macroeconomics', lp: 6, areas: ['basis'] },
  { id: 'bm_metrics', name: 'BM Econometrics', lp: 6, areas: ['basis'] },

  // Schwerpunktbereich (exklusiv)
  { id: 'sm_sem_emda', name: 'SM Seminar Empirical Methods and Data Analysis', lp: 6, areas: ['schwerpunkt'], specializations: ['emda'] },
  { id: 'sm_sem_mep', name: 'SM Seminar Markets and Economic Policy', lp: 6, areas: ['schwerpunkt'], specializations: ['mep'] },
  { id: 'sm_sem_mdb', name: 'SM Seminar Market Design and Behaviour', lp: 6, areas: ['schwerpunkt'], specializations: ['mdb'] },
  { id: 'sm_sem_ecc', name: 'SM Seminar Energy and Climate Change', lp: 6, areas: ['schwerpunkt'], specializations: ['ecc'] },

  // Überschneidungen: Schwerpunktbereich & Ergänzungsbereich Economics
  { id: 'am_empirical', name: 'AM Empirical Methods', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda', 'mep', 'mdb', 'ecc'] },
  { id: 'am_comp', name: 'AM Computational Methods', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep', 'mdb', 'ecc'] },
  { id: 'am_sel_metrics', name: 'AM Selected Methods in Economics', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep', 'mdb', 'ecc'] },
  { id: 'sm_emda_1', name: 'SM Empirical Methods and Data Analysis I', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda'] },
  { id: 'sm_emda_2', name: 'SM Empirical Methods and Data Analysis II', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda'] },
  { id: 'sm_emda_3', name: 'SM Empirical Methods and Data Analysis III', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda'] },
  { id: 'sm_emda_4', name: 'SM Empirical Methods and Data Analysis IV', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda'] },
  { id: 'sm_emda_5', name: 'SM Empirical Methods and Data Analysis V', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['emda'] },
  { id: 'sm_mep_1', name: 'SM Markets and Economic Policy I', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep'] },
  { id: 'sm_mep_2', name: 'SM Markets and Economic Policy II', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep'] },
  { id: 'sm_mep_3', name: 'SM Markets and Economic Policy III', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep'] },
  { id: 'sm_mep_4', name: 'SM Markets and Economic Policy IV', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep'] },
  { id: 'sm_mep_5', name: 'SM Markets and Economic Policy V', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mep'] },
  { id: 'sm_mdb_1', name: 'SM Market Design and Behavior I', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mdb'] },
  { id: 'sm_mdb_2', name: 'SM Market Design and Behavior II', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mdb'] },
  { id: 'sm_mdb_3', name: 'SM Market Design and Behavior III', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mdb'] },
  { id: 'sm_mdb_4', name: 'SM Market Design and Behavior IV', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mdb'] },
  { id: 'sm_mdb_5', name: 'SM Market Design and Behavior V', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['mdb'] },
  { id: 'sm_ecc_1', name: 'SM Energy and Climate Change I', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['ecc'] },
  { id: 'sm_ecc_2', name: 'SM Energy and Climate Change II', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['ecc'] },
  { id: 'sm_ecc_3', name: 'SM Energy and Climate Change III', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['ecc'] },
  { id: 'sm_ecc_4', name: 'SM Energy and Climate Change IV', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['ecc'] },
  { id: 'sm_ecc_5', name: 'SM Energy and Climate Change V', lp: 6, areas: ['schwerpunkt', 'ergaenzung_econ'], specializations: ['ecc'] },

  // Ergänzungsbereich Economics (exklusiv)
  { id: 'em_sem_econ', name: 'EM Seminar Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_eee', name: 'SM Energy and Environmental Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_peme', name: 'SM Political Economics and Media Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_fti', name: 'SM Frictions, Technology, and Inequality', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_ape', name: 'SM Advanced Public Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_abe', name: 'SM Advanced Behavioural Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'bm_he3', name: 'BM Health Economics III', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'em_eio', name: 'EM Economics of Incentives in Organizations', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sm_me', name: 'SM Media Economics', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sa_econ_1', name: 'Studies Abroad in Economics I', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sa_econ_2', name: 'Studies Abroad in Economics II', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sa_econ_3', name: 'Studies Abroad in Economics III', lp: 6, areas: ['ergaenzung_econ'] },
  { id: 'sa_econ_4', name: 'Studies Abroad in Economics IV', lp: 18, areas: ['ergaenzung_econ'] },

  // Ergänzungsbereich MSS (exklusiv)
  { id: 'sm_tax_1', name: 'SM Taxation I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_tax_2', name: 'SM Taxation II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_ctrl_1', name: 'SM Controlling I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_ctrl_2', name: 'SM Controlling II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_acc_1', name: 'SM Accounting I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_acc_2', name: 'SM Accounting II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_be', name: 'SM Business Ethics', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_sd', name: 'SM Strategic Development', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_shrm', name: 'SM Strategic Human Resource Management', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_sm', name: 'SM Strategic Management', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_fin_1', name: 'SM Finance I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_fin_2', name: 'SM Finance II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_fin_3', name: 'SM Finance III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_brand', name: 'SM Brand Management', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_customer', name: 'SM Customer Management', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_mpm', name: 'SM Marketing Performance Management', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_dsm', name: 'SM Digital Strategy and Marketing', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_sca_1', name: 'BM Supply Chain Analytics I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_sca_2', name: 'BM Supply Chain Analytics II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_sco', name: 'SM Supply Chain Operations', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_scs', name: 'SM Supply Chain Strategy', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_scp', name: 'SM Supply Chain Planning', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_sisc', name: 'SM Selected Issues in Supply Chain Management III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_is_1', name: 'BM Information Systems I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_is_2', name: 'BM Information Systems II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_dt', name: 'BM Digital Transformation', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_is_3', name: 'SM Information Systems III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_cpi', name: 'BM Comparative Political Institutions', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_cpe', name: 'BM Comparative Political Economy', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_dtp', name: 'BM Democratic Theory and Practice', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_ir', name: 'BM International Relations', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_ep', name: 'BM European Politics', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_stps_1', name: 'SM Special Topics Political Science I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_stps_2', name: 'SM Special Topics Political Science II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_soc_2', name: 'BM Sociology II Sociological Theory', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_soc_3', name: 'BM Sociology III Contemporary Societies: Social Structure and Social Change', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_eg_1', name: 'EM Economic Geography I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_eg_2', name: 'EM Economic Geography II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_eg_3', name: 'EM Economic Geography III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_eg_4', name: 'EM Economic Geography IV', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_iep', name: 'EM Introduction to Economic Psychology', lp: 12, areas: ['ergaenzung_mss'] },
  { id: 'em_mtm_ems', name: 'EM Media and Technology Management - Enterprises, Markets, and Strategies', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_mtm_si1', name: 'EM Media and Technology Management - Selected Issues I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_mtm_si2', name: 'EM Media and Technology Management - Selected Issues II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'em_mtm_rp', name: 'EM Media and Technology Management - Research and Publications', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_da_1', name: 'BM Data Analytics I', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_da_2', name: 'BM Data Analytics II', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_da_3', name: 'BM Data Analytics III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_da_4', name: 'BM Data Analytics IV', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'bm_da_5', name: 'BM Data Analytics V', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sm_ab_3', name: 'SM Analytics for Business III', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sa_mss_1', name: 'Studies Abroad I (Economics)', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sa_mss_2', name: 'Studies Abroad II (Economics)', lp: 6, areas: ['ergaenzung_mss'] },
  { id: 'sa_mss_3', name: 'Studies Abroad III (Economics)', lp: 12, areas: ['ergaenzung_mss'] },

  // Masterarbeit
  { id: 'thesis', name: 'Masterarbeit', lp: 30, areas: ['thesis'] }
];
